kind: Deployment
apiVersion: apps/v1
metadata:
  name: escrow
  namespace: default-1653588364307
  uid: 9902de51-c554-4aac-9bec-f24729a23703
  resourceVersion: '618663'
  generation: 2
  creationTimestamp: '2022-05-26T18:06:23Z'
  annotations:
    deployment.kubernetes.io/revision: '2'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: apps/v1
      time: '2022-05-26T18:12:45Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:progressDeadlineSeconds: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
          f:template:
            f:metadata:
              f:labels:
                .: {}
                f:app: {}
            f:spec:
              f:containers:
                k:{"name":"escrow"}:
                  .: {}
                  f:env:
                    .: {}
                    k:{"name":"CosmosDbConnectionString"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"MONGODB_COLLECTION"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"MONGODB_DATABASE"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:ports:
                    .: {}
                    k:{"containerPort":80,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:protocol: {}
                    k:{"containerPort":8080,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:protocol: {}
                  f:resources:
                    .: {}
                    f:limits:
                      .: {}
                      f:cpu: {}
                      f:memory: {}
                    f:requests:
                      .: {}
                      f:cpu: {}
                      f:memory: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
              f:dnsPolicy: {}
              f:nodeSelector: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2022-05-26T18:12:47Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
      subresource: status
spec:
  replicas: 5
  selector:
    matchLabels:
      app: escrow
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: escrow
    spec:
      containers:
        - name: escrow
          image: fincodevregistry.azurecr.io/signingservice:latest
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
          env:
            - name: CosmosDbConnectionString
              value: >-
                mongodb://signer2db:jSzd2VTgYrg3TibXUUvQMm8S7VBmYrTeuX0u30U5HbD4vCPU7C22EutihIPnwAQj22ln0kszAAZJ6epvqpUAFw==@signer2db.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@signer2db@
            - name: MONGODB_DATABASE
              value: signer2-db
            - name: MONGODB_COLLECTION
              value: signer2db-collection
            - name: PARTICIPANTID
              value: "2"
            - name: AZURE_CLIENT_ID
              value: "765cb1df-e786-475f-82d5-5d7ebf9813f2"
            - name: AZURE_CLIENT_SECRET
              value: "vWZ8Q~KK4PphJJ-KVUFBvN16TFOU6CYt-7M8wb6H"
            - name: AZURE_TENANT_ID
              value: "2dc7c48e-0569-4780-805b-400ec5d480a1"
            - name: AZURE_KEYVAULT_URL
              value: "https://escrowvault.vault.azure.net/"               
          resources:
            limits:
              cpu: '256'
              memory: 11400G
            requests:
              cpu: '0'
              memory: '0'
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 2
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2022-05-26T18:12:47Z'
      lastTransitionTime: '2022-05-26T18:12:47Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2022-05-26T18:12:47Z'
      lastTransitionTime: '2022-05-26T18:06:23Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "escrow-6d774f9dcf" has successfully progressed.

