kind: Deployment
apiVersion: apps/v1
metadata:
  name: signingservice
  uid: 8be55fd7-d728-4962-bdd6-f7771c86c8cc
  resourceVersion: '20572'
  generation: 1
  creationTimestamp: '2022-05-24T21:13:10Z'
  annotations:
    deployment.kubernetes.io/revision: '1'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: apps/v1
      time: '2022-05-24T21:13:10Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:progressDeadlineSeconds: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
          f:template:
            f:metadata:
              f:labels:
                .: {}
                f:app: {}
            f:spec:
              f:containers:
                k:{"name":"signingservice"}:
                  .: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:ports:
                    .: {}
                    k:{"containerPort":80,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:protocol: {}
                    k:{"containerPort":8080,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:protocol: {}
                  f:resources:
                    .: {}
                    f:limits:
                      .: {}
                      f:cpu: {}
                      f:memory: {}
                    f:requests:
                      .: {}
                      f:cpu: {}
                      f:memory: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
              f:dnsPolicy: {}
              f:nodeSelector: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2022-05-24T21:13:11Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
      subresource: status
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signingservice
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: signingservice
    spec:
      containers:
        - name: signingservice
          image: 010531221017.dkr.ecr.us-east-2.amazonaws.com/finco:latest
          env:
            - name: CosmosDbConnectionString
              value: "mongodb://signer1db:eJ3qG0RwbpAufNw7etvE9cu8N6LvwajpGfK1y4fXjbKfN6Ptg7paNEmPfHJylyut0fyLh1NPcl2JqaTvgsTtMg==@signer1db.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@signer1db@"
            - name: MONGODB_DATABASE
              value: "signer1-db"
            - name: MONGODB_COLLECTION
              value: "signer1db-collection"
            - name: PARTICIPANTID
              value: "1"
            - name: AZURE_CLIENT_ID
              value: "765cb1df-e786-475f-82d5-5d7ebf9813f2"
            - name: AZURE_CLIENT_SECRET
              value: "vWZ8Q~KK4PphJJ-KVUFBvN16TFOU6CYt-7M8wb6H"
            - name: AZURE_TENANT_ID
              value: "2dc7c48e-0569-4780-805b-400ec5d480a1"
            - name: AZURE_KEYVAULT_URL
              value: "https://fincovault.vault.azure.net/"
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: '256'
              memory: 11400G
            requests:
              cpu: '2'
              memory: 129M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2022-05-24T21:13:11Z'
      lastTransitionTime: '2022-05-24T21:13:11Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2022-05-24T21:13:11Z'
      lastTransitionTime: '2022-05-24T21:13:10Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "signingservice-8697d566bc" has successfully progressed.

